### ISSUE TITLE
Layout issue on maintenance page

### ISSUE THREAD

**Issue by FullGreenGN** [AzuriomCommunity/Theme-DarkWave#1]
Bonjour,
Je rencontre ce probleme avec la page de maintenance cf image si joint
![Capture d'écran 2023-02-26 135344](https://user-images.githubusercontent.com/61293366/221411713-e2714229-a40d-4a2d-b657-487de6265e9d.png)

**Comment by MrMicky-FR** [comment]
Fixed in 9949a813b5d9d5c8f38aa1125c48fef08ac00e37, release will be published soon
